import mermaid from 'mermaid';

mermaid.initialize({
  startOnLoad: false,
  theme: 'base',
  securityLevel: 'loose',
  fontFamily: 'IBM Plex Sans, Segoe UI, sans-serif',
  fontSize: 14,
  themeVariables: {
    primaryColor: '#2d2d3f',
    primaryBorderColor: '#ffffff',
    primaryTextColor: '#ffffff',
    lineColor: '#ffffff',
    edgeLabelBackground: 'transparent',
    clusterBkg: '#2d2d3f',
    nodeBorder: '#ffffff',
    mainBkg: '#2d2d3f',
    secondaryColor: '#2d2d3f',
    tertiaryColor: '#2d2d3f',
    titleColor: '#ffffff',
    attributeBackgroundColorEven: '#2d2d3f',
    attributeBackgroundColorOdd: '#1e1e2e',

    background: '#1e1e2e',
    textColor: '#ffffff',
    actorBkg: '#2d2d3f',
    actorTextColor: '#ffffff',
    actorBorder: '#ffffff',
    actorLineColor: '#ffffff',
    signalColor: '#ffffff',
    signalTextColor: '#ffffff',
    labelTextColor: '#ffffff',
    labelBoxBkgColor: '#2d2d3f',
    labelBoxBorderColor: '#ffffff',
    loopTextColor: '#ffffff',
    noteBkgColor: '#2d2d3f',
    noteTextColor: '#ffffff',
    noteBorderColor: '#ffffff',
    activationBorderColor: '#ffffff',
    activationBkgColor: '#2d2d3f',
    sequenceNumberColor: '#ffffff',
    sectionBkgColor: '#2d2d3f',
    altSectionBkgColor: '#1e1e2e',
    sectionBkgColor2: '#2d2d3f',

    classText: '#ffffff',
    fillType0: '#2d2d3f',
    fillType1: '#1e1e2e',
    fillType2: '#2d2d3f',
    fillType3: '#1e1e2e',
    fillType4: '#2d2d3f',
    fillType5: '#1e1e2e',
    fillType6: '#2d2d3f',
    fillType7: '#1e1e2e',
  },
  flowchart: { htmlLabels: true, useMaxWidth: true },
  sequence: { useMaxWidth: true, mirrorActors: false },
});
